config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    root 'homes#top'
    resources :genres
    resources :products
    resources :customers
  end
  scope module: "customers" do
    root 'homes#top'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resource :customers, only: %i[show edit update]
    resources :products
    patch 'cart_products/increase'
    patch 'cart_products/decrease'
    delete 'cart_products/destroy_all'
    resources :cart_products
    resources :delivery_addresses
    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, except: %i[edit update destroy]
  end
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :customer
  validates :quantity, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :email
    validates :family_name
    validates :given_name
    validates :family_name_kana
    validates :given_name_kana
    validates :postal_code
    validates :address
    validates :phone_number
    validates :is_active
  end

  enum prefecture:{
    北海道:1,
    青森県:2,
    岩手県:3,
    宮城県:4,
    秋田県:5,
    山形県:6,
    福島県:7,
    茨城県:8,
    栃木県:9,
    群馬県:10,
    埼玉県:11,
    千葉県:12,
    東京都:13,
    神奈川県:14,
    新潟県:15,
    富山県:16,
    石川県:17,
    福井県:18,
    山梨県:19,
    長野県:20,
    岐阜県:21,
    静岡県:22,
    愛知県:23,
    三重県:24,
    滋賀県:25,
    京都府:26,
    大阪府:27,
    兵庫県:28,
    奈良県:29,
    和歌山県:30,
    鳥取県:31,
    島根県:32,
    岡山県:33,
    広島県:34,
    山口県:35,
    徳島県:36,
    香川県:37,
    愛媛県:38,
    高知県:39,
    福岡県:40,
    佐賀県:41,
    長崎県:42,
    熊本県:43,
    大分県:44,
    宮崎県:45,
    鹿児島県:46, 
    沖縄県:47
  }

  def full_name
    self.family_name + self.given_name
  end

  def active_for_authentication?
    super && (self.is_active == true)
  end
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :customer

  with_options presence: true do
    validates :name
    validates :postal_code
    validates :prefecture
    validates :address
  end

  enum prefecture: {
    北海道: 0,
    青森県: 1,
    岩手県: 2,
    宮城県: 3,
    秋田県: 4,
    山形県: 5,
    福島県: 6,
    茨城県: 7,
    栃木県: 8,
    群馬県: 9,
    埼玉県: 10,
    千葉県: 11,
    東京都: 12,
    神奈川県: 13,
    新潟県: 14,
    富山県: 15,
    石川県: 16,
    福井県: 17,
    山梨県: 18,
    長野県: 19,
    岐阜県: 20,
    静岡県: 21,
    愛知県: 22,
    三重県: 23,
    滋賀県: 24,
    京都府: 25,
    大阪府: 26,
    兵庫県: 27,
    奈良県: 28,
    和歌山県: 29,
    鳥取県: 30,
    島根県: 31,
    岡山県: 32,
    広島県: 33,
    山口県: 34,
    徳島県: 35,
    香川県: 36,
    愛媛県: 37,
    高知県: 38,
    福岡県: 39,
    佐賀県: 40,
    長崎県: 41,
    熊本県: 42,
    大分県: 43,
    宮崎県: 44,
    鹿児島県: 45, 
    沖縄県: 46
  }
  def full_address
    self.postal_code + self.prefecture + self.name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products, dependent: :destroy

  with_options presence: true do
    validates :shipping_name
    validates :shipping_postal_code
    validates :shipping_prefecture
    validates :shipping_address
    validates :postage
    validates :charge
    validates :payment_method
    validates :order_status
  end

  enum payment_method: {
    クレジットカード: 0,
    銀行振り込み: 1,
    代金引換え: 2
  }

  enum order_status: {
    製作中: 0,
    発送準備中: 1,
    発送済み: 2
  }

  enum shipping_prefecture: {
    北海道: 0,
    青森県: 1,
    岩手県: 2,
    宮城県: 3,
    秋田県: 4,
    山形県: 5,
    福島県: 6,
    茨城県: 7,
    栃木県: 8,
    群馬県: 9,
    埼玉県: 10,
    千葉県: 11,
    東京都: 12,
    神奈川県: 13,
    新潟県: 14,
    富山県: 15,
    石川県: 16,
    福井県: 17,
    山梨県: 18,
    長野県: 19,
    岐阜県: 20,
    静岡県: 21,
    愛知県: 22,
    三重県: 23,
    滋賀県: 24,
    京都府: 25,
    大阪府: 26,
    兵庫県: 27,
    奈良県: 28,
    和歌山県: 29,
    鳥取県: 30,
    島根県: 31,
    岡山県: 32,
    広島県: 33,
    山口県: 34,
    徳島県: 35,
    香川県: 36,
    愛媛県: 37,
    高知県: 38,
    福岡県: 39,
    佐賀県: 40,
    長崎県: 41,
    熊本県: 42,
    大分県: 43,
    宮崎県: 44,
    鹿児島県: 45, 
    沖縄県: 46
  }
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  enum production_status: {
    製作中: 0,
    製作完了: 1
  }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  mount_uploader :image, ImageUploader

  with_options presence: true do
    validates :name
    validates :description
    validates :image
    validates :price, numericality: {greater_than_or_equal_to: 0}
    validates :genre
    validates :sales_status
  end

  enum genre: {
    スフレ: 0,
    ベイクド: 1,
    ニューヨーク: 2,
    レア: 3
  }

  enum sales_status: {
    準備中: 0,
    販売可: 1,
    在庫切れ: 2,
    販売終了: 3
  }

end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admins_product_path(@product)
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admins_product_path(@product)
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image, :price, :genre, :sales_status)
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    case resource
    when Customer
      customers_path
    when Admin
      admins_root_path
    end
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/helpers/customers/products_helper.rb
module Customers::ProductsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_admins_header.html.erb
<header>
  <nav>
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav nav-list">
        <% if admin_signed_in? %>
          <li><%= link_to"ログアウト", destroy_admin_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to"新規登録", new_admin_registration_path %></li>
          <li><%= link_to"ログイン", new_admin_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_customers_header.html.erb
<header>
  <nav>
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav nav-list">
        <% if customer_signed_in? %>
          <li><%= link_to "商品一覧", products_path %></li>
          <li><%= link_to "マイページ", customers_path %></li>
          <li><%= link_to "カート", cart_products_path %></li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to"新規登録", new_customer_registration_path %></li>
          <li><%= link_to"ログイン", new_customer_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
  </head>

  <body>
    <% if request.fullpath.include?("admins") %>
      <%= render 'layouts/admins_header' %>
    <% else%>
      <%= render 'layouts/customers_header' %>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-primary text-center" role="alert"><strong><%= notice %></strong></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger text-center" role="alert"><strong><%= alert %></strong></div>
    <% end %>
    <%= yield %>
  </body>
</html>