config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    root 'homes#top'
    resources :genres
    resources :products
    resources :customers
  end
  scope module: "customers" do
    root 'homes#top'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resource :customers, only: %i[show edit update]
    resources :products
    patch 'cart_products/increase'
    patch 'cart_products/decrease'
    delete 'cart_products/destroy_all'
    resources :cart_products
    resources :delivery_addresses
    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, except: %i[edit update destroy]
  end
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  mount_uploader :image, ImageUploader

  with_options presence: true do
    validates :name
    validates :description
    validates :image
    validates :price, numericality: {greater_than_or_equal_to: 0}
    validates :genre
    validates :sales_status
  end

  enum genre: {
    スフレ: 0,
    ベイクド: 1,
    ニューヨーク: 2,
    レア: 3
  }

  enum sales_status: {
    準備中: 0,
    販売可: 1,
    在庫切れ: 2,
    販売終了: 3
  }

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admins_product_path(@product)
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admins_product_path(@product)
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image, :price, :genre, :sales_status)
  end
end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/customers/products_helper.rb
module Customers::ProductsHelper
end

app/views/admins/products/edit.html.erb
<h1>Admins::Products#edit</h1>
<p>Find me in app/views/admins/products/edit.html.erb</p>

<%= form_with model: @product, url: admins_product_path(@product), local:true do |f| %>
  <%= render "layouts/error_messages", obj: @product %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.label :genre %>
    <%= f.select :genre, [["スフレ", "スフレ"], ["ベイクド", "ベイクド"], ["ニューヨーク", "ニューヨーク"], ["レア", "レア"]], {prompt: "選択されていません"} %>
  </div>
  <div>
    <%= f.label :sales_status %>
    <%= f.select :sales_status, [["準備中", "準備中"], ["販売可", "販売可"], ["在庫切れ", "在庫切れ"], ["販売終了", "販売終了"]], {prompt: "選択されていません"} %>
  </div>

  <%= f.submit %>
<% end %>

app/views/admins/products/index.html.erb
<h1>Admins::Products#index</h1>
<p>Find me in app/views/admins/products/index.html.erb</p>

<% @products.each do |product| %>
  <div>
    <div><%= image_tag product.image.to_s, :size => '200x200' %></div>
    <div><%= product.name %></div>
    <div><%= product.description %></div>
    <div><%= product.genre %></div>
    <div><%= product.price %></div>
    <div><%= product.sales_status %></div>
    <%= link_to "詳細",  admins_product_path(product) %>
  </div>
<% end %>

app/views/admins/products/new.html.erb
<h1>Admins::Products#new</h1>
<p>Find me in app/views/admins/products/new.html.erb</p>

<%= form_with model: @product, url: admins_products_path, local:true do |f| %>
  <%= render "layouts/error_messages", obj: @product %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.label :genre %>
    <%= f.select :genre, [["スフレ", "スフレ"], ["ベイクド", "ベイクド"], ["ニューヨーク", "ニューヨーク"], ["レア", "レア"]], {prompt: "選択されていません"} %>
  </div>
  <div>
    <%= f.label :sales_status %>
    <%= f.select :sales_status, [["準備中", "準備中"], ["販売可", "販売可"], ["在庫切れ", "在庫切れ"], ["販売終了", "販売終了"]], {prompt: "選択されていません"} %>
  </div>

  <%= f.submit %>
<% end %>

app/views/admins/products/show.html.erb
<h1>Admins::Products#show</h1>
<p>Find me in app/views/admins/products/show.html.erb</p>

<div><%= image_tag @product.image.to_s, :size => '200x200' %></div>
<div><%= @product.name %></div>
<div><%= @product.description %></div>
<div><%= @product.genre %></div>
<div><%= @product.price %></div>
<div><%= @product.sales_status %></div>
<%= link_to "編集",  edit_admins_product_path(@product) %>